Repository WildCodeSchool/orleans-202103-php-project-interim, pull requests merged in 2021-06, with the labels that each got.

#7 Init
  assets/app.js
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  yarn.lock
Labels: Corrections done, Reviewed

#10 US13: Encart "Nos valeurs/nos sevices" sur la page d'accueil
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Reviewed

#12 dev to master
  assets/app.js
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  src/Controller/AdminController.php
  src/Controller/CompanyController.php
  src/Controller/StudentController.php
  templates/_navbar.html.twig
  templates/_navbar_admin.html.twig
  templates/_navbar_company.html.twig
  templates/_navbar_student.html.twig
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/company/index.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
  templates/student/index.html.twig
  yarn.lock
Labels: Reviewed

#17 S02_US9 : Changed navbar style and fixed links
  assets/images/logo.png
  assets/styles/app.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  src/Controller/CompanyController.php
  src/Controller/StudentController.php
  templates/_navbar.html.twig
  templates/_navbar_admin.html.twig
  templates/_navbar_student.html.twig
  templates/_navbar_user.html.twig
  templates/base.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
  webpack.config.js
Labels: Reviewed

#18 US13: Header
  assets/images/pexels-fauxels-3182757.jpg
  assets/styles/header.scss
  assets/styles/variables.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#21 US13: Banner "Nos valeurs/nos services"
  assets/images/pexels-fauxels-3183150.jpg
  assets/styles/home.scss
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#25 S02 : Style fix
  assets/styles/header.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
Labels: Reviewed

#24 S02_US9 : Fixed navbar on home page
  assets/styles/header.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
Labels: Reviewed

#23 S02US10_Footer création d'un footer
  assets/images/facebook.png
  assets/images/insta.png
  assets/images/linkedin.png
  assets/images/youtube.png
  assets/styles/footer.scss
  templates/base/_footer.html.twig
  templates/layout.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
Labels: Corrections done, Reviewed

#27 FIX: fix padding et dossier
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/component/_navbar_user.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
Labels: Reviewed

#22 S01US14: Création du contact utilisateur
  assets/styles/contact.scss
  assets/styles/variables.scss
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/base.html.twig
  templates/contact/index.html.twig
Labels: Corrections done, Reviewed

#29 US25: formulaire de demande de devis
  src/Controller/CompanyController.php
  src/Entity/QuotationRequest.php
  src/Form/QuotationRequestType.php
  templates/company/quotationRequest.html.twig
Labels: Corrections done, Reviewed

#34 Sprint 2
  assets/images/facebook.png
  assets/images/insta.png
  assets/images/linkedin.png
  assets/images/logo.png
  assets/images/pexels-fauxels-3182757.jpg
  assets/images/pexels-fauxels-3183150.jpg
  assets/images/youtube.png
  assets/styles/app.scss
  assets/styles/contact.scss
  assets/styles/footer.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  src/Controller/CompanyController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/StudentController.php
  src/Entity/Contact.php
  src/Entity/QuotationRequest.php
  src/Form/ContactType.php
  src/Form/QuotationRequestType.php
  templates/_navbar_admin.html.twig
  templates/_navbar_student.html.twig
  templates/base.html.twig
  templates/company/quotationRequest.html.twig
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/component/_navbar_user.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
  webpack.config.js
Labels: Reviewed

#36 Fix_quotationRequest
  templates/base.html.twig
Labels: Reviewed

#35 Fix_link
  src/Controller/ContactController.php
  src/Entity/Contact.php
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_user.html.twig
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#31 fix assert
  src/Controller/ContactController.php
  src/Entity/Contact.php
Labels: Corrections done, Reviewed

#26 S02_US08 Createaccount part1
  composer.json
  composer.lock
  config/packages/security.yaml
  migrations/Version20210609074401.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/UserAuthenticator.php
  templates/component/_navbar.html.twig
  templates/security/login.html.twig
Labels: Corrections done, Reviewed

#37 S02US10: modifiaction du style
  assets/images/facebook.png
  assets/images/insta.png
  assets/images/linkedin.png
  assets/images/youtube.png
  assets/styles/app.scss
  assets/styles/footer.scss
  templates/component/_footer.html.twig
Labels: Corrections done, Reviewed

#38 Fix_navbar
  src/Controller/HomeController.php
Labels: Reviewed

#28 lister admin offre
  assets/styles/adminJob.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20210614192518.php
  src/Controller/AdminJobController.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/JobFixtures.php
  src/Entity/Company.php
  src/Entity/Contact.php
  src/Entity/Job.php
  src/Form/JobType.php
  src/Repository/CompanyRepository.php
  src/Repository/JobRepository.php
  symfony.lock
  templates/admin_job/_delete_form.html.twig
  templates/admin_job/_form.html.twig
  templates/admin_job/edit.html.twig
  templates/admin_job/index.html.twig
  templates/base.html.twig
  templates/component/_navbar_admin.html.twig
  templates/layout_admin.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#39 Fix font
  assets/fonts/PoetsenOne-Regular.ttf
  assets/fonts/TwCenMTCondensedBold.ttf
  assets/fonts/TwCenMTCondensedRegular.ttf
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/layout_admin.html.twig
Labels: Corrections done, Reviewed

#41 fix_footer
  templates/component/_footer.html.twig
Labels: Reviewed

#42 fix size card
  assets/styles/adminJob.scss
  templates/admin_job/index.html.twig
Labels: Reviewed

#40 admin delete job
  templates/admin_job/_delete_form.html.twig
  templates/admin_job/index.html.twig
Labels: Reviewed

#44 S03 us14 contact
  src/Controller/ContactController.php
  src/Entity/Contact.php
  templates/email/newContactEmail.html.twig
Labels: Reviewed

#46 Fix font-style
  assets/styles/footer.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#49 S03US29_admin_edit_job
  src/Controller/AdminJobController.php
  src/Entity/Job.php
  src/Form/AdminJobType.php
  templates/admin_job/_form.html.twig
  templates/admin_job/edit.html.twig
Labels: Reviewed

#50 Fix add faker
  assets/styles/adminJob.scss
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/JobFixtures.php
  templates/admin_job/index.html.twig
Labels: Reviewed

#51 style login
  templates/security/login.html.twig
Labels: Reviewed

#52 fix size card
  assets/styles/adminJob.scss
Labels: Reviewed

#53 dev to master
  assets/styles/adminJob.scss
  assets/styles/footer.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  composer.lock
  config/services.yaml
  src/Controller/AdminJobController.php
  src/Controller/CompanyController.php
  src/Controller/ContactController.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/JobFixtures.php
  src/Entity/Contact.php
  src/Entity/Job.php
  src/Form/AdminJobType.php
  templates/admin_job/_form.html.twig
  templates/admin_job/edit.html.twig
  templates/admin_job/index.html.twig
  templates/email/layoutEmail.html.twig
  templates/email/newContactEmail.html.twig
  templates/email/quotationRequestEmail.html.twig
  templates/home/index.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: Review requested

#56 Fix card style
  assets/styles/adminJob.scss
  templates/admin_job/index.html.twig
Labels: Reviewed

#54 S03_US04 Liste comptes Entreprise
  migrations/Version20210617164905.php
  src/Controller/AdminController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Company.php
  src/Entity/User.php
  templates/admin/companiesList.html.twig
Labels: Corrections done, Reviewed

#60 S04US12_HomeOffers: ajout des cards sur la home
  src/Controller/HomeController.php
  src/DataFixtures/UserFixtures.php
  templates/home/index.html.twig
Labels: Reviewed

#58 S04US11_UserOffers:ajout des offres cotés utlisateur
  src/Controller/OfferController.php
  templates/component/_navbar.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#59 S03_US23 : Listed jobs for a single company
  migrations/Version20210617100928.php
  src/Controller/CompanyController.php
  src/DataFixtures/JobFixtures.php
  src/DataFixtures/StudyFieldFixtures.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Entity/StudyField.php
  src/Repository/StudyFieldRepository.php
  templates/company/list_jobs.html.twig
  templates/component/_navbar_user.html.twig
  templates/layout_company.html.twig
Labels: Reviewed

#61 FIX_navbar: ajout des active pour surbrillance
  templates/component/_navbar.html.twig
Labels: Reviewed

#64 Fix_UserFixtures
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#66 FIX_style offre
  src/Controller/OfferController.php
  templates/offer/index.html.twig
Labels: Reviewed

#63 fix style card (hope i done)
  assets/app.js
  assets/styles/adminJob.scss
  package-lock.json
  package.json
  templates/admin_job/index.html.twig
  templates/base.html.twig
  yarn.lock
Labels: Reviewed

#67 S03_US22 : Add an offer when being connected as a company
  src/Controller/CompanyController.php
  src/Entity/Job.php
  src/Form/JobType.php
  templates/company/list_jobs.html.twig
  templates/job/_form.html.twig
  templates/job/new.html.twig
Labels: Reviewed

#69 S04_US13 Valeurs/Services
  assets/images/pexels-cottonbro-7439129.jpg
  assets/images/pexels-fauxels-3184338.jpg
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#72 Fix title
  assets/styles/adminJob.scss
  templates/admin/companiesList.html.twig
  templates/admin_job/index.html.twig
  templates/component/_navbar_admin.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#65 bouton connexion/deconnexion
  config/packages/security.yaml
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  templates/component/_navbar.html.twig
Labels: Corrections done, Reviewed

#73 FIX_responsive_homepage
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Conflict resolved, Reviewed

#76 fix_card_entreprise_style
  templates/admin/companiesList.html.twig
Labels: Reviewed

#74 S04_US31 : View for a single offer
  assets/styles/app.scss
  assets/styles/variables.scss
  src/Controller/JobController.php
  templates/job/show.html.twig
Labels: Reviewed
