Repository WildCodeSchool/orleans-202103-php-project-interim, pull requests merged in 2021-07, with the labels that each got.

#62 S04_US32 Liste des comptes Etudiants (côté admin)
  migrations/Version20210621143129.php
  migrations/Version20210622095703.php
  migrations/Version20210623122118.php
  src/Controller/AdminController.php
  src/DataFixtures/StudentFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Student.php
  src/Entity/User.php
  src/Repository/StudentRepository.php
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
  templates/component/_navbar_admin.html.twig
Labels: Conflict resolved

#78 S04 us11 filter offer
  src/Controller/OfferController.php
  src/DataFixtures/JobFixtures.php
  src/DataFixtures/StudyFieldFixtures.php
  src/Entity/FilterStudyField.php
  src/Form/FilterStudyFieldType.php
  templates/offer/index.html.twig
Labels: Corrections done, Reviewed

#75 barre de recherche admin entreprise
  src/Controller/AdminController.php
  src/Data/SearchData.php
  src/Form/SearchType.php
  src/Repository/CompanyRepository.php
  templates/admin/companies_list.html.twig
Labels: Reviewed

#79 fix offer card
  templates/offer/index.html.twig
Labels: Reviewed

#80 S05US6: ajout des deux bouton supprimé et des deux méthode delete dans le con…
  src/Controller/AdminController.php
  src/Entity/Company.php
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
Labels: Reviewed

#85 FIX: ajout du style pour le filtre des offres
  assets/styles/app.scss
  assets/styles/variables.scss
  src/Form/FilterStudyFieldType.php
  templates/offer/index.html.twig
Labels: Reviewed

#84 sort student by studyfield
  migrations/Version20210701144714.php
  src/Controller/AdminController.php
  src/DataFixtures/StudentFixtures.php
  src/Entity/Student.php
  src/Entity/StudyField.php
  src/Form/FilterStudyFieldType.php
  templates/admin/students_list.html.twig
Labels: Reviewed

#83 S05_US9: New navbar
  assets/images/logo.png
  assets/styles/app.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/component/_navbar_user.html.twig
  templates/layout_admin.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
Labels: Reviewed

#82 S04_US20 company info
  src/Controller/CompanyController.php
  templates/company/profile.html.twig
Labels: Reviewed

#87 S05_US22: Changed studyfield row in form
  src/Form/JobType.php
Labels: Reviewed

#86 S05_US31: Changed cards for company jobs
  templates/company/list_jobs.html.twig
Labels: Reviewed

#89 fixlabel
  src/Form/FilterStudyFieldType.php
Labels: Reviewed

#90 S05US15: displaying student user info
  src/Controller/StudentController.php
  src/Entity/Student.php
  templates/student/profile.html.twig
Labels: Reviewed

#91 FIX: fix de la taille du main et création variable de scss
  assets/styles/app.scss
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/offer/index.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#94 fix migration [URGENT]
  migrations/Version20210609074401.php
  migrations/Version20210614192518.php
  migrations/Version20210617100928.php
  migrations/Version20210617164905.php
  migrations/Version20210621143129.php
  migrations/Version20210622095703.php
  migrations/Version20210623122118.php
  migrations/Version20210701144714.php
  migrations/Version20210706081901.php
Labels: Reviewed

#93 S05_US17: Send a mail to postulate to an offer
  src/Controller/StudentController.php
  templates/email/postulateEmail.html.twig
  templates/job/show.html.twig
  templates/offer/index.html.twig
Labels: Corrections done, Reviewed

#95 register US
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: Corrections done, Reviewed

#97 S05: changed logo
  assets/images/logo.png
Labels: Reviewed

#98 S05_US9: Navbar style and added name
  templates/component/_navbar.html.twig
Labels: Reviewed

#100 S05_US17: Changed postulate button on home page
  templates/home/index.html.twig
Labels: Reviewed

#101 S05_US9: Student navbar fix
  templates/component/_navbar.html.twig
Labels: Reviewed

#99 S05 us34 pagination
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yaml
  config/packages/translation.yaml
  src/Controller/AdminController.php
  symfony.lock
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
Labels: Corrections done, Reviewed

#102 suppression du bouton devis
  templates/component/_footer.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#103 fix du style des filtres et création du filtre
  src/Controller/AdminJobController.php
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
  templates/admin_job/index.html.twig
Labels: Reviewed

#104 fix register
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: Reviewed

#105 S05_US24: Denied access to editing jobs from another company
  src/Controller/CompanyController.php
Labels: Reviewed

#108 S05: Fixed signing in link in navbar
  templates/component/_navbar.html.twig
Labels: Reviewed

#107 S05: Style fix title and footer
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
  templates/base.html.twig
Labels: Reviewed

#106 add all pagination
  assets/styles/app.scss
  src/Controller/AdminJobController.php
  src/Controller/CompanyController.php
  src/Controller/OfferController.php
  templates/admin_job/index.html.twig
  templates/company/list_jobs.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#109 S05: Fix remove a title and style
  templates/company/profile.html.twig
Labels: Reviewed

#110 add user and jobs
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/StudentFixtures.php
Labels: Reviewed

#113 S05: Fixed links to see details
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#115 limiter_caractères_card
  templates/admin/students_list.html.twig
  templates/admin_job/index.html.twig
  templates/company/list_jobs.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#114 Fix nav profile
  templates/company/profile.html.twig
  templates/component/_navbar.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#116 fixed profil bug
  templates/student/profile.html.twig
Labels: Reviewed

#118 S05_US35: Added price listé
  assets/images/contrat.jpg
  assets/images/recrutement.jpg
  src/Controller/HomeController.php
  templates/home/index.html.twig
  templates/home/price_list.html.twig
Labels: Corrections done, Reviewed

#117 création d'un refresh
  src/Controller/AdminJobController.php
  src/Controller/OfferController.php
  src/Entity/FilterStudyField.php
  src/Form/FilterStudyFieldType.php
  templates/admin_job/index.html.twig
  templates/component/_navbar.html.twig
  templates/offer/index.html.twig
Labels: Corrections done, Reviewed

#123 fix_background
  assets/images/background.jpg
  assets/styles/app.scss
Labels: Reviewed

#122 studyfield_show
  templates/job/show.html.twig
Labels: Reviewed

#120 S05US41: lost password
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20210707084433.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
Labels: Corrections done, Reviewed

#121 S05US37 add studyfield on card
  assets/styles/adminJob.scss
  templates/company/list_jobs.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#111 Dev to master
  assets/images/background.jpg
  assets/images/contrat.jpg
  assets/images/recrutement.jpg
  assets/styles/adminJob.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20210707084433.php
  src/Controller/AdminJobController.php
  src/Controller/CompanyController.php
  src/Controller/HomeController.php
  src/Controller/OfferController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/StudentFixtures.php
  src/Entity/FilterStudyField.php
  src/Entity/ResetPasswordRequest.php
  src/Entity/User.php
  src/Form/ChangePasswordFormType.php
  src/Form/FilterStudyFieldType.php
  src/Form/RegistrationFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
  templates/admin_job/index.html.twig
  templates/base.html.twig
  templates/company/list_jobs.html.twig
  templates/company/profile.html.twig
  templates/component/_navbar.html.twig
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/job/show.html.twig
  templates/offer/index.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#125 fix_hide carac
  templates/offer/index.html.twig
Labels: Reviewed

#124 S05_US9: Responsive navbar
  templates/component/_navbar.html.twig
Labels: Reviewed

#126 Dev to master
  templates/component/_navbar.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#127 S05: Fix the access to quotation request button
  src/Controller/CompanyController.php
  templates/home/price_list.html.twig
Labels: Reviewed

#128 S05 us16 edit student
  src/Controller/StudentController.php
  src/Entity/Student.php
  src/Form/StudentEditType.php
  src/Form/StudentType.php
  templates/layout_student.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#129 fix more text
  src/DataFixtures/JobFixtures.php
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#130 Dev to master
  src/Controller/CompanyController.php
  src/Controller/StudentController.php
  src/DataFixtures/JobFixtures.php
  src/Entity/Student.php
  src/Form/StudentEditType.php
  src/Form/StudentType.php
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/layout_student.html.twig
  templates/offer/index.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#133 fixing student/company subscription
  migrations/Version20210709084116.php
  src/Controller/SecurityController.php
  src/Controller/StudentController.php
  src/Entity/Student.php
  templates/student/profile.html.twig
Labels: Reviewed

#134 S05: Fixed titles and removed order by
  templates/company/list_jobs.html.twig
  templates/offer/index.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#131 S05: changed header img and favicon
  assets/images/favicon.png
  assets/images/pexels-fauxels-3182757.jpg
Labels: Reviewed

#132 S05: Added prices in navbar for users and companies
  templates/component/_navbar.html.twig
Labels: Reviewed

#137 fix style card and background
  assets/styles/adminJob.scss
  assets/styles/app.scss
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#141 FIX : Changed button style
  templates/admin_job/edit.html.twig
Labels: Reviewed

#139 FIX : Changed titles
  templates/job/show.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#138 FIX : Changed logo
  assets/images/logo.png
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
Labels: Reviewed

#140 FIX : Corrected routes
  src/Controller/AdminJobController.php
  src/Controller/OfferController.php
  src/Controller/SecurityController.php
  templates/admin_job/edit.html.twig
Labels: Reviewed

#142 fix style filtre et insertion placeholder
  src/Form/FilterStudyFieldType.php
  templates/admin/students_list.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#143 FIX : Changed block titles
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
  templates/admin_job/edit.html.twig
  templates/base.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/list_jobs.html.twig
  templates/company/profile.html.twig
  templates/company/quotationRequest.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/job/edit.html.twig
  templates/job/new.html.twig
  templates/job/show.html.twig
  templates/layout_admin.html.twig
  templates/layout_company.html.twig
  templates/layout_student.html.twig
  templates/offer/index.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  templates/student/_form.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#145 FIX_migrations
  migrations/Version20210707084433.php
  migrations/Version20210709084116.php
  migrations/Version20210709133515.php
  migrations/Version20210712092008.php
Labels: Reviewed

#146 profil style modified
  assets/styles/profile.scss
  templates/company/profile.html.twig
  templates/student/profile.html.twig
  webpack.config.js
Labels: Reviewed

#147 profiles -> profile misstake
  webpack.config.js
Labels: Reviewed

#148 dev to master
  assets/styles/profile.scss
  templates/company/profile.html.twig
  templates/student/profile.html.twig
  webpack.config.js
Labels: Reviewed

#149 FIX_offersTitle
  templates/offer/index.html.twig
Labels: Reviewed

#150 FIX_form_background_color
  assets/styles/contact.scss
  assets/styles/variables.scss
Labels: Reviewed

#153 FIX : Block title for companies on their profile
  templates/company/profile.html.twig
Labels: Reviewed

#152 FIX : Price list and home style
  templates/home/index.html.twig
  templates/home/price_list.html.twig
Labels: Reviewed

#151 ajout de la fonctionnalité upload reste la modification des upload à …
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20210712142731.php
  src/Entity/Student.php
  src/Form/StudentType.php
  symfony.lock
  templates/student/_form.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#154 fixed left card of profiles
  templates/company/profile.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#155 récupértion des par un lien coté admin
  templates/admin/students_list.html.twig
Labels: Reviewed

#158 modified images of profiles
  templates/company/profile.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#159 fix style
  src/Form/ResetPasswordRequestFormType.php
  templates/reset_password/check_email.html.twig
  templates/reset_password/request.html.twig
Labels: Reviewed

#161 FIX_mails
  templates/email/newContactEmail.html.twig
  templates/email/postulateEmail.html.twig
  templates/email/quotationRequestEmail.html.twig
  templates/reset_password/email.html.twig
Labels: Reviewed

#156 FIX_flash_messages
  assets/styles/app.scss
  src/Controller/ContactController.php
  src/Controller/StudentController.php
  templates/base.html.twig
  templates/component/_flash.html.twig
Labels: Corrections done, Reviewed

#162 dev to master
  assets/styles/app.scss
  assets/styles/contact.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20210712142731.php
  src/Controller/AdminController.php
  src/Controller/AdminJobController.php
  src/Controller/CompanyController.php
  src/Controller/ContactController.php
  src/Controller/OfferController.php
  src/Controller/StudentController.php
  src/Entity/Student.php
  src/Form/ResetPasswordRequestFormType.php
  src/Form/StudentType.php
  symfony.lock
  templates/admin/index.html.twig
  templates/admin/students_list.html.twig
  templates/base.html.twig
  templates/company/index.html.twig
  templates/company/profile.html.twig
  templates/component/_flash.html.twig
  templates/email/newContactEmail.html.twig
  templates/email/postulateEmail.html.twig
  templates/email/quotationRequestEmail.html.twig
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/offer/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/student/_form.html.twig
  templates/student/index.html.twig
  templates/student/profile.html.twig
Labels: Review requested

#165 suppression des liens télécharger dans le edit de l'étudiant
  src/Form/StudentType.php
Labels: Reviewed

#163 fix style
  templates/company/list_jobs.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#164 updating readme file
  README.md
Labels: Corrections done, Reviewed

#166 DEV TO MASTER
  README.md
  src/Form/StudentType.php
  templates/company/list_jobs.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#179 fix_edit_and_delete
  src/Controller/AdminJobController.php
Labels: Reviewed

#177 FIX : Admin navbar and removed a button in the price list
  templates/component/_navbar.html.twig
  templates/home/price_list.html.twig
Labels: Reviewed

#175 FIX_postulate_Email
  src/Controller/StudentController.php
  templates/email/confirmedApplicationEmail.html.twig
  templates/email/postulateEmail.html.twig
Labels: Reviewed

#178 fix Legal notice
  migrations/Version20210713101519.php
  src/Controller/LegalNoticeController.php
  src/DataFixtures/LegalNoticeFixtures.php
  src/Entity/LegalNotice.php
  src/Form/LegalNoticeType.php
  src/Repository/LegalNoticeRepository.php
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/legal_notice/_delete_form.html.twig
  templates/legal_notice/_form.html.twig
  templates/legal_notice/edit.html.twig
  templates/legal_notice/index.html.twig
  templates/legal_notice/new.html.twig
Labels: Reviewed

#180 fix page number
  templates/offer/index.html.twig
Labels: Reviewed

#185 FIX : Changed footer style and removed useless part of login page
  assets/styles/app.scss
  templates/component/_footer.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#181 FIX : fixed some links and buttons
  src/Controller/StudentController.php
  templates/component/_navbar.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
Labels: Reviewed

#182 FIX responsive card
  assets/styles/adminJob.scss
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#186 FIX_orderUsers
  src/Controller/AdminController.php
  src/Repository/CompanyRepository.php
  src/Repository/StudentRepository.php
Labels: Reviewed

#183 fix page number admin
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
Labels: Corrections done, Reviewed

#176 FIX_orderOffers
  src/Controller/OfferController.php
Labels: Corrections done, Reviewed

#188 FIX : Admin cards
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
Labels: Reviewed

#189 fix text
  templates/home/index.html.twig
Labels: Reviewed

#192 fix reponsive filtre
  templates/admin/students_list.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#193 Fix icons
  assets/images/company.png
  assets/images/student.png
  templates/company/profile.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#187 FIX : Force company fill infos
  src/Controller/CompanyController.php
Labels: Corrections done, Reviewed

#191 FIX filtre admin
  src/Controller/AdminController.php
  src/Form/FilterStudyFieldType.php
Labels: Reviewed

#194 changement de placeholder
  src/Form/SearchType.php
Labels: Reviewed

#190 FIX : Legals mentions style
  templates/legal_notice/_delete_form.html.twig
  templates/legal_notice/edit.html.twig
  templates/legal_notice/index.html.twig
  templates/legal_notice/new.html.twig
Labels: Reviewed

#184 Dev to master
  assets/images/company.png
  assets/images/student.png
  assets/styles/adminJob.scss
  assets/styles/app.scss
  migrations/Version20210713101519.php
  src/Controller/AdminController.php
  src/Controller/AdminJobController.php
  src/Controller/CompanyController.php
  src/Controller/LegalNoticeController.php
  src/Controller/OfferController.php
  src/Controller/StudentController.php
  src/DataFixtures/LegalNoticeFixtures.php
  src/Entity/LegalNotice.php
  src/Form/FilterStudyFieldType.php
  src/Form/LegalNoticeType.php
  src/Form/SearchType.php
  src/Repository/CompanyRepository.php
  src/Repository/LegalNoticeRepository.php
  src/Repository/StudentRepository.php
  templates/admin/companies_list.html.twig
  templates/admin/students_list.html.twig
  templates/company/profile.html.twig
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/email/confirmedApplicationEmail.html.twig
  templates/email/postulateEmail.html.twig
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/legal_notice/_delete_form.html.twig
  templates/legal_notice/_form.html.twig
  templates/legal_notice/edit.html.twig
  templates/legal_notice/index.html.twig
  templates/legal_notice/new.html.twig
  templates/offer/index.html.twig
  templates/security/login.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#195 FIX_birthdate
  src/Form/StudentType.php
Labels: Reviewed

#196 ajout des assert
  src/Entity/Student.php
Labels: Reviewed

#197 Dev to master
  src/Entity/Student.php
  src/Form/StudentType.php
Labels: Reviewed

#200 FIX_levelEdit
  src/Form/StudentType.php
Labels: Reviewed

#198 fixed responsive profil
  templates/company/profile.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#202 ajout automatique des champs du form pour le devis
  src/Controller/CompanyController.php
Labels: Reviewed

#199 fix tarif reponsive
  templates/home/price_list.html.twig
Labels: Reviewed

#201 fix-button-size-mention
  templates/legal_notice/_delete_form.html.twig
  templates/legal_notice/index.html.twig
Labels: Reviewed

#203 dev to master
  src/Controller/CompanyController.php
  src/Form/StudentType.php
  templates/company/profile.html.twig
  templates/home/price_list.html.twig
  templates/legal_notice/_delete_form.html.twig
  templates/legal_notice/index.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#204 margin sur les cards
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/offer/index.html.twig
Labels: Corrections done, Reviewed

#205 fixed text tarifs page
  templates/home/price_list.html.twig
Labels: Reviewed

#206 fixed size btn tarifs page
  templates/home/price_list.html.twig
Labels: Reviewed

#207 FIX_w3c
  public/uploads/coverLetters/.gitignore
  public/uploads/resumes/.gitignore
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#208 FIX_StudyField
  src/Form/FilterStudyFieldType.php
Labels: Reviewed

#210 ajout d'un px-1
  templates/student/profile.html.twig
Labels: Reviewed

#209 FIX : Style for homepage and pricelist
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/home/price_list.html.twig
Labels: Reviewed

#211 fix card text
  assets/styles/adminJob.scss
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#213 FIX_siret
  src/Entity/Company.php
Labels: Reviewed

#214 FIX: redirected to profile modification after registering
  src/Controller/SecurityController.php
  src/Entity/User.php
Labels: Reviewed

#217 FIX : changed birthdate and form organisation
  src/Form/StudentType.php
  templates/company/profile.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#215 another card fix
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#216 FIX : Added buttons in price list and changed a row in quotation request form
  src/Form/QuotationRequestType.php
  templates/home/price_list.html.twig
Labels: Reviewed

#219 FIX : Changed youtube link
  templates/component/_footer.html.twig
Labels: Reviewed

#218 FIX : Changed header img for responsive
  assets/styles/home.scss
Labels: Reviewed

#212 Dev to master
  assets/styles/adminJob.scss
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  public/uploads/coverLetters/.gitignore
  public/uploads/resumes/.gitignore
  src/Controller/SecurityController.php
  src/Entity/Company.php
  src/Entity/User.php
  src/Form/FilterStudyFieldType.php
  src/Form/QuotationRequestType.php
  src/Form/StudentType.php
  templates/company/profile.html.twig
  templates/component/_footer.html.twig
  templates/home/index.html.twig
  templates/home/price_list.html.twig
  templates/offer/index.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#220 fix studyfield
  src/Form/StudentType.php
  templates/student/_form.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#221 Dev to master
  src/Form/StudentType.php
  templates/student/_form.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#223 fixed profil student can't load
  templates/student/profile.html.twig
Labels: Reviewed

#224 suppression du boutton en trop
  templates/admin_job/edit.html.twig
Labels: Reviewed

#225 TEST_PROD
  migrations/Version20210726094419.php
Labels: Reviewed

#226 FIX : Readme and User Manual
  README.md
  USER_MANUAL.md
Labels: Reviewed

#222 ajout de sécurisation
  src/Entity/Job.php
Labels: Corrections done, Reviewed

#227 FIX : Changed routes and secured job detail
  src/Controller/JobController.php
  templates/home/index.html.twig
  templates/offer/index.html.twig
Labels: Corrections done, Reviewed

#229 FIX_student_form
  src/Form/StudentType.php
Labels: Reviewed

#228 Dev to master
  README.md
  USER_MANUAL.md
  migrations/Version20210726094419.php
  src/Controller/JobController.php
  src/Entity/Job.php
  src/Form/StudentType.php
  templates/admin_job/edit.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
  templates/student/profile.html.twig
Labels: Reviewed

#230 fix style reset_password
  src/Form/ChangePasswordFormType.php
  src/Form/RegistrationFormType.php
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed

#231 add_password_check
  src/Form/RegistrationFormType.php
Labels: Reviewed

#234 FIX: env
  .env
Labels: Reviewed

#233 FIX: error message template
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Corrections done, Reviewed

#232 Dev to master
  .env
  src/Form/ChangePasswordFormType.php
  src/Form/RegistrationFormType.php
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed

#235 Fix footer
  .github/workflows/deploy_prod.yaml
  src/Controller/CompanyController.php
  templates/company/_form.html.twig
  templates/layout_student.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
Labels: Reviewed
